FROM node:18-alpine AS base
# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./


COPY tsconfig.json ./

# Install dependencies
RUN npm ci

RUN npm install -g @nestjs/cli

RUN npm install
# Copy all the files
COPY . .

# Build the Next.js app
# RUN npm run start:dev